# Enumerates non-Microsoft scheduled tasks

Get-ScheduledTask | Where-Object -Property TaskPath -NotLike '\MICROSOFT\*'

# Event 4702 (Task Updated), Events 106 / 4698 (Tasks Created)

Get-EventLog -LogName Security | Where-Object -Property EventID -Match "4702|106|4698"

# Grab WMI Activity Logs via PowerShell

$WMIProv = Get-WinEvent -ListProvider "Microsoft-Windows-WMI-Activity"
$WMIProv.Events | Where-Object {$_.LogLink.LogName -eq "Microsoft-Windows-WMI-Activity/Operational"}

# Grab associated Windows Event IDs from the WMI logs

$WMIEvents = $WMIProv.Events | Where-Object {$_.LogLink.LogName -eq "Microsoft-Windows-WMI-Activity/Operational"}
$WMIEvents | Select-Object -Property Id

# Register events generated by a class, and subscribe to the registered events (EX: Process Creation Event)

Register-CimIndicationEvent -ClassName 'Win32_ProcessStartTrace' -SourceIdentifier "ProcessStarted"
Get-Event -SourceIdentifier "ProcessStarted"
